language: node_js
node_js: 12
before_script:
  - npm install -g @babel/core @babel/cli @babel/plugin-syntax-class-properties
script:
  - npx babel site.js --out-file site.js --plugins=@babel/plugin-syntax-class-properties
  - cp index.html 404.html
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
  fqdn: autoyato.halomademeapc.com